export default [
  `BROtato Chip`,
  "BROkémon",
  "Hulk BROgan",
  "Tony BROmo",
  "Edgar Allen BRO",
  "BROan of Arc",
  "Dunkin’ BROnuts",
  "BROklahoma",
  "BRO hard or BRO home",
  "BROhemian Rhapsody",
  "Seth BROgen",
  "Frosty the BROman",
  "That 70’s BRO",
  "Last of the BROhicans",
  "BROklahoma",
  "ChicagBRO",
  "BROtatoes",
  "BROfessional",
  "sloppy BROS",
  "SupercalifragilisticecspiealaBROcious",
  "BROvember",
  "Bronunciation",
  "U.F.BRO",
  "BRObot",
  "macaBROni",
  "MexiBRO",
  "BROtel California",
  "G.I. BRO",
  "BROmance",
  "BROducer",
  "BROordination",
  "BROgrammer",
  "BROtastic!",
];